/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        cmdMostrar = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        cmdGuardar = new javax.swing.JButton();
        txtContrasenaNueva = new javax.swing.JPasswordField();
        cmdGuardarNueva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseñas Guardadas"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 90));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        cmdCambiar.setText("Cambiar");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        cmdBorrar.setText("Limpiar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, 140));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 20));

        cmdGuardar.setText("Guardar contraseña");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 30));

        txtContrasenaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasenaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, 20));

        cmdGuardarNueva.setText("Guardar nueva contraseña");
        cmdGuardarNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardarNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 170, 30));

        jLabel2.setText("Ingrese contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setText("Ingrese nueva contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtContrasena.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            txtContrasena.requestFocusInWindow();
            txtContrasena.selectAll();
            cmdGuardar.setEnabled(true);
        } else {
            String cont;

            cont = txtContrasena.getText();
            m = new Password(cont);

            JOptionPane.showMessageDialog(this, "Contraseña Guardada");
            cmdMostrar.setEnabled(true);
            cmdCambiar.setEnabled(true);
            txtContrasena.setEditable(false);
            cmdGuardar.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void txtContrasenaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaNuevaActionPerformed

    private void cmdGuardarNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarNuevaActionPerformed
        if (txtContrasenaNueva.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese la nueva contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            txtContrasenaNueva.requestFocusInWindow();
            txtContrasenaNueva.selectAll();
        } else {
            String contn;

            contn = txtContrasenaNueva.getText();
            p = new Password(contn);
            p.NiveldeSeguridad();
            JOptionPane.showMessageDialog(this, "Nueva contraseña guardada");

            cmdMostrar.setEnabled(true);
            cmdCambiar.setEnabled(true);
            txtContrasenaNueva.setEditable(false);
        }
        cmdGuardarNueva.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdGuardarNuevaActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtContrasena.setText("");
        txtContrasenaNueva.setText("");
        txtResultado.setText("");
        txtContrasena.requestFocusInWindow();

        cmdGuardar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(false);
        cmdGuardarNueva.setEnabled(false);
        cmdBorrar.setEnabled(true);

        txtContrasena.setEditable(true);
        txtContrasenaNueva.setEditable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed
        txtContrasena.setEditable(false);
        txtContrasenaNueva.setEditable(true);
        cmdGuardarNueva.setEnabled(true);
        txtContrasenaNueva.requestFocusInWindow();
        txtContrasenaNueva.setText("");

        JOptionPane.showMessageDialog(this, "Digite una nueva contraseña");

        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdCambiar.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        if (txtContrasenaNueva.getText().trim().isEmpty()) {
            txtResultado.setText("Su contraseña es: " + m.getContraseña() + "\n"
                + m.NiveldeSeguridad());
        } else {
            txtResultado.setText("Su contraseña es: " + m.getContraseña() + "\n"
                + m.NiveldeSeguridad() + "\n"
                + "Su nueva contraseña es: " + p.getContraseña() + "\n"
                + p.NiveldeSeguridad());
        }

        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdCambiar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdGuardarNueva;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtContrasenaNueva;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
